FROM node:15 as production
LABEL org.opencontainers.image.source https://github.com/Alphasians/AINA
ARG github_token
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --production --ignore-scripts

COPY . .

CMD ["npm", "run", "start"]
